### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by micksp** [leftyio/google_tag_manager#2]
Hi
I'd love to use this package, however I can't find how. For instance where do I store the container ID? I suspect there needs to be something in the environment to make this work?

**Comment by khangahs** [comment]
What's the difference between pushEvent and push? Please clarify the usage. Thank you.

**Comment by lejard-h** [comment]
This package is a simple interop around `dataLayer.push` you can find the documentation here https://developers.google.com/tag-manager/quickstart

And `pushEvent` is a shortcut for
```dart
push({
 'event': event and,
 ....
})
```

**Comment by nytoan** [comment]
So it's not for mobile but web ?

**Comment by lejard-h** [comment]
Yes Google Tag Manger is only for web.
